export const dataProperties = [
  {
    id: 1,
    location: "Porto, Portugal",
    price: 500000,
    bedrooms: 3,
    bathroom: 3,
    image: "propertie1.jpeg",
    star: 4.9,
    meters: 430,
    description:
      "No coração da encantadora cidade do Porto, uma oportunidade única para adquirir um espetacular apartamento de 75 metros quadrados, combinando conforto, elegância e um ambiente natural inigualável. Esta moradia, situada numa zona tranquila e bem servida, é um refúgio de paz e beleza que certamente o encantará. Ao entrar neste acolhedor lar, será recebido por um hall que o conduz a uma casa de banho completa com banheira, ideal para relaxar após um longo dia. Um espaçoso salão se funde com a cozinha através de portas deslizantes.",
  },
  {
    id: 2,
    location: "Lisboa, Portugal",
    price: 150000,
    bedrooms: 2,
    bathroom: 2,
    image: "propertie2.jpeg",
    star: 4,
    meters: 230,
    description:
      "Em Lisboa, a cidade das sete colinas, esta propriedade oferece uma combinação perfeita de conforto e elegância em 75 metros quadrados, localizada numa zona tranquila e bem comunicada. Ao entrar neste espaço acolhedor, encontrará uma casa de banho completa com banheira, ideal para momentos de relaxamento, e um generoso salão que se liga com a cozinha através de portas deslizantes.",
  },
  {
    id: 3,
    location: "Braga, Portugal",
    price: 350000,
    bedrooms: 5,
    bathroom: 2,
    image: "propertie3.jpg",
    star: 5,
    meters: 90,
    description:
      "Localizada em Braga, cidade histórica com um toque moderno, esta moradia com 90 metros quadrados oferece um espaço único que mistura o antigo e o contemporâneo. Ao entrar, um hall leva-o a uma espaçosa sala de estar, ideal para a família, e uma cozinha que se integra com a sala através de portas deslizantes.",
  },
  {
    id: 4,
    location: "Faro, Portugal",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie4.webp",
    star: 4.2,
    meters: 120,
    description:
      "Situada em Faro, no Algarve, esta propriedade oferece 120 metros quadrados de puro conforto e elegância. A casa possui uma ampla área social e uma cozinha moderna integrada, perfeita para receber amigos e familiares.",
  },
  {
    id: 5,
    location: "Coimbra, Portugal",
    price: 600000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie5.jpg",
    star: 4.1,
    meters: 87,
    description:
      "Em Coimbra, cidade dos estudantes, encontra-se esta propriedade aconchegante e bem estruturada, ideal para uma vida tranquila. Os 87 metros quadrados são bem distribuídos, proporcionando um ambiente harmonioso com cozinha integrada.",
  },
  {
    id: 6,
    location: "Aveiro, Portugal",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie6.jpg",
    star: 3.7,
    meters: 220,
    description:
      "Em Aveiro, a 'Veneza de Portugal', esta moradia de 220 metros quadrados oferece uma experiência única com canais e beleza natural ao redor. Conta com uma espaçosa sala de estar e uma cozinha moderna, proporcionando conforto e elegância.",
  },
  {
    id: 7,
    location: "Sintra, Portugal",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie7.jpg",
    star: 4.5,
    meters: 430,
    description:
      "Em Sintra, rodeada por natureza e charme histórico, esta propriedade de 430 metros quadrados oferece um espaço amplo e acolhedor. Com detalhes únicos e áreas sociais generosas, é o local perfeito para quem valoriza história e conforto.",
  },
  {
    id: 8,
    location: "Évora, Portugal",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie8.jpeg",
    star: 4.5,
    meters: 330,
    description:
      "Situada na cidade de Évora, Patrimônio da UNESCO, esta moradia de 330 metros quadrados oferece um ambiente histórico e sofisticado. Um hall de entrada conduz ao espaço de estar que integra-se com a cozinha moderna e funcional.",
  },
  {
    id: 9,
    location: "Guimarães, Portugal",
    price: 120000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie9.jpeg",
    star: 2,
    meters: 380,
    description:
      "Em Guimarães, berço de Portugal, esta propriedade de 380 metros quadrados é ideal para quem aprecia um estilo de vida confortável com um toque de história. Possui uma sala ampla conectada com a cozinha, proporcionando um espaço agradável para a convivência.",
  },
  {
    id: 10,
    location: "Viana do Castelo, Portugal",
    price: 210000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie10.jpg",
    star: 4.1,
    meters: 270,
    description:
      "No coração de Viana do Castelo, esta propriedade de 270 metros quadrados é perfeita para quem aprecia uma vida à beira-mar. Com amplas áreas e uma cozinha moderna, este espaço oferece um ambiente acolhedor e relaxante.",
  },
  {
    id: 11,
    location: "Cascais, Portugal",
    price: 980000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie11.jpg",
    star: 5,
    meters: 430,
    description:
      "Em Cascais, cidade costeira perto de Lisboa, encontra-se esta luxuosa propriedade de 430 metros quadrados, ideal para quem procura elegância e conforto. Com uma sala espaçosa e uma cozinha funcional, é o local perfeito para relaxar com vista para o Atlântico.",
  },
  {
    id: 12,
    location: "Portimão, Portugal",
    price: 310000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie12.jpeg",
    star: 3.9,
    meters: 76,
    description:
      "Em Portimão, cidade famosa por suas praias, esta moradia de 76 metros quadrados é ideal para quem valoriza proximidade com o mar. Um espaço acolhedor com cozinha prática e áreas bem aproveitadas.",
  },
  {
    id: 13,
    location: "Lagos, Portugal",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie13.jpg",
    star: 4.8,
    meters: 290,
    description:
      "Localizada em Lagos, esta propriedade de 290 metros quadrados oferece a combinação perfeita entre elegância e conforto. Ideal para relaxar após um dia nas praias do Algarve.",
  },
  {
    id: 14,
    location: "Albufeira, Portugal",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie14.jpg",
    star: 4.9,
    meters: 180,
    description:
      "Em Albufeira, esta moradia de 180 metros quadrados proporciona um refúgio acolhedor perto das praias mais famosas do Algarve. Um espaço ideal para quem busca conforto e momentos de lazer à beira-mar.",
  },
  {
    id: 15,
    location: "Setúbal, Portugal",
    price: 500000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie15.jpeg",
    star: 4.1,
    meters: 287,
    description:
      "Em Setúbal, uma cidade encantadora com vista para o Sado, esta propriedade de 287 metros quadrados é perfeita para quem deseja um espaço acolhedor com um toque de sofisticação.",
  },
  {
    id: 16,
    location: "Chaves, Portugal",
    price: 100000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie16.jpeg",
    star: 4,
    meters: 290,
    description:
      "Na histórica cidade de Chaves, esta moradia de 290 metros quadrados oferece um ambiente acolhedor com um toque medieval. Perfeita para quem deseja viver num local cheio de história e beleza.",
  },
];
